import './globals.css'; // Assuming you have global styles
import { Lato } from 'next/font/google';
import { ReactNode } from 'react';

const lato = Lato({ subsets: ['latin'], weight: ['100', '300', '400', '700', '900'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={lato.className}>
        {children}
      </body>
    </html>
  );
}
